name: bldr-io/bldr
description: 'Build System with YAML in mind'

profiles:
    default:
        description: 'Development Profile'
        tasks:
            - prepare
            - lint
            - phpcs
            - test

tasks:
    prepare:
        description: 'Cleans up old builds and prepares the new one'
        calls:
            -
                type: filesystem:remove
                arguments: [build/coverage, build/logs]
            -
                type: filesystem:mkdir
                arguments: [build/coverage, build/logs]
            -
                type: filesystem:touch
                arguments: [build/coverage/index.html]
            -
                type: exec
                arguments: [composer install --prefer-dist]
    lint:
        describe: 'Lints the files of the project'
        calls:
            -
                type: apply
                fileset: src/**/*.php
                arguments: [php -l]

    phpcs:
        description: 'Runs the PHP Code Sniffer'
        calls:
            -
                type: exec
                arguments:
                    - php bin/phpcs
                    - -p
                    - --standard=build/phpcs.xml
                    - --report=checkstyle
                    - --report-file=build/logs/checkstyle.xml
                    - src/
    test:
        description: 'Runs the PHPUnit Tests'
        calls:
            -
                type: exec
                failOnError: true
                arguments:
                    - php bin/phpunit
                    - --coverage-text=php://stdout
