language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm, 5.6, 5.5

before_script:
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source

script:
  - ./bin/bldr build -p default

after_script:
   - php bin/coveralls -v
