language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm, 5.6, 5.5

before_script:
  - composer self-update
  - composer install

script:
  - ./bin/bldr build -p default

after_script:
   - php vendor/bin/coveralls -v
