language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm, 5.6, 5.5

before_script:
  - composer self-update
  - composer global require bldr-io/bldr="~0.1.0"

script:
  - bldr build default
